dataset = "dataset.xyz"
cell_length = 50
label = "!cc"  # no label cc
recalc_descriptors = true
output = "."
training_cutoffs = [ 1, 2, 3, 4, 5, 6, 7, 8 ]
potential_exponents = 1
n_alpha_values = 10

[sr_hypers]
cutoff = 3.0
max_radial = 6
max_angular = 4
atomic_gaussian_width = 0.3
center_atom_weight = 1.0
radial_basis = { Gto = {} }
cutoff_function = { ShiftedCosine = { width = 0.5 } }

[lr_hypers]
cutoff = 3.0
max_radial = 4
max_angular = 4
atomic_gaussian_width = 1.0
center_atom_weight = 1.0
radial_basis = { Gto = {} }
